# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(blank=True, max_length=300)),
                ('post_photo', models.ImageField(blank=True, upload_to='post_images/')),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('post_sharecount', models.IntegerField(blank=True, null=True)),
                ('post_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cseday2016.Location')),
            ],
            options={
                'ordering': ['-post_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw', models.CharField(blank=True, max_length=10)),
                ('about_me', models.CharField(blank=True, max_length=300)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('last_location', models.CharField(blank=True, max_length=300)),
                ('verification_status', models.CharField(choices=[('a', 'active'), ('d', 'deactive'), ('o', 'other'), ('p', 'pending'), ('s', 'suspended')], default='p', max_length=2)),
                ('verification_code', models.CharField(default='123456', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cseday2016.UserProfile'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_sharedfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cseday2016.Post'),
        ),
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_got_blocked', to='cseday2016.UserProfile'),
        ),
        migrations.AddField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_blocked', to='cseday2016.UserProfile'),
        ),
    ]
